spring:
  application:
    name: eureka-consumer
server:
  port: 1003
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka/

resilience4j:
  circuitbreaker:
    backends:
      backendA:
        registerHealthIndicator: true
        slidingWindowSize: 100
  retry:
    backends:
      backendA:
        maxAttempts: 3
        waitDuration: 100
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2


